version: '3.4'

services:
  web:
    image: "rabbitmqweb:dev"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - rabbitconnstr=amqp://guest:guest@rabbitmq:5672
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mynetwork
  healthui:
    image: "xabarilcoding/healthchecksui"
    environment: 
      - HealthChecksUI:HealthChecks:0:Name=rabbitmqweb
      - HealthChecksUI:HealthChecks:0:Uri=http://web:80/health
    ports:
      - "5000:80"
    networks:
      - mynetwork
networks: 
  mynetwork: {}